sudo: false

language: node_js

node_js: stable

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - echo '' > .npmrc

install:
  - npm install -g bower gulp
  - npm install

before_script:
  - bower install

script:
  - gulp
  - gulp styles

after_script:
  - cd ./dist
  - git init
  - git config user.name "PandoraBox Cat"
  - git config user.email "cat@pandorabox.org.cn"
  - git add .
  - git commit -m "PandoraBox Cat push some files"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" HEAD:master

branches:
  only:
    - develop

env:
  global:
    - GH_REF: github.com/More-Link/More-link.github.io.git
