name: Source Code
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [8, 22]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx bower install
      - run: npx tsdown
      - name: Use Node.js 8
        uses: actions/setup-node@v4
        with:
          node-version: 8
      - run: npm run build
      - name: Upload version Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
