name: Source Code
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [8, 22]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx bower install
      - run: npx tsdown
      - name: Use Node.js 8
        uses: actions/setup-node@v4
        with:
          node-version: 8
      - run: npm run build
      - name: Upload version Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # merge:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download version Artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: artifacts
  #     - run: |
  #         mkdir -p merged-dist
  #         find artifacts/ -name "dist-*" -type d -exec cp -r {} merged-dist/ \;
  #     - name: Upload merged Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: merged-dist
